window.FORM1_READING = {
  ctw: [
    { id:"f1ctw01", taskType:"ctw", title:"Morning walk", level:"easy", text:"Many people say that a short walk is one of the [simplest|6] ways to feel [better|3]. A quiet walk each [morning|4] can lift your [mood|2] and wake up your [body|3]. You do not need special [shoes|3] to begin." },
    { id:"f1ctw02", taskType:"ctw", title:"At the library", level:"easy", text:"The town [library|3] is open every [day|1] except Sunday. You can [borrow|3] up to five books at a [time|2]. Please return them before the due [date|2] so that others can [read|2] them too." },
    { id:"f1ctw03", taskType:"ctw", title:"Cooking rice", level:"easy", text:"Cooking rice is [easy|3] once you learn the [steps|2]. First, wash the rice in cold [water|3]. Then add the right [amount|3] of water and [heat|2] the pot. Wait until the rice is [soft|2] before you eat." },
    { id:"f1ctw04", taskType:"ctw", title:"A rainy day", level:"easy", text:"It started to [rain|2] just after lunch. We could not [play|2] outside, so we stayed [inside|3] all afternoon. My sister found an old [game|2], and we had a lot of [fun|1]. By evening the sky was [clear|3] again." },
    { id:"f1ctw05", taskType:"ctw", title:"Helping at home", level:"easy", text:"Everyone in my family helps with the [chores|3]. I wash the [dishes|4] after dinner, and my brother takes out the [trash|3]. On weekends we [clean|3] the whole house [together|4]. It feels [good|2] to share the work." },
    { id:"f1ctw06", taskType:"ctw", title:"The school garden", level:"easy", text:"Our class started a small [garden|4] behind the school. We planted [seeds|3] in the spring and gave them [water|3] every day. Now the plants are tall and [green|3]. Soon we will pick the [tomatoes|3] and share them with everyone." },
    { id:"f1ctw07", taskType:"ctw", title:"A new pet", level:"easy", text:"Last week we got a new [puppy|4]. He is very [small|3] and loves to [sleep|3] on the sofa. My job is to feed him twice a [day|1] and take him for a short [walk|2]. He makes our home feel [happy|3]." },
    { id:"f1ctw08", taskType:"ctw", title:"Weekend market", level:"easy", text:"Every Saturday a small [market|3] opens near the river. Farmers bring [fresh|3] fruit and vegetables to [sell|2]. The bread there is always [warm|2] and smells [wonderful|6]. I like to buy some [apples|3] before we go home." },
    { id:"f1ctw09", taskType:"ctw", title:"Learning to swim", level:"easy", text:"When I was young, I was [afraid|3] of the water. My father taught me to [swim|2] one summer at the lake. At first I could only [float|3], but soon I felt [safe|2]. Now swimming is my favorite [sport|3]." },
    { id:"f1ctw10", taskType:"ctw", title:"A birthday plan", level:"easy", text:"My friend's [birthday|5] is next week. We want to give her a [surprise|4] party at my house. I will bake a [cake|2], and Tom will bring the [balloons|4]. We hope she will be very [happy|3] when she arrives." },
    { id:"f1ctw11", taskType:"ctw", title:"City transport", level:"med", text:"Cities depend on reliable public [transport|5] to move people [efficiently|4]. When buses and trains run on [schedule|4], fewer drivers choose their own [vehicles|4]. This can reduce traffic and lower [pollution|4] across the whole [region|3]. Good planning also makes travel [affordable|6] for families with low incomes." },
    { id:"f1ctw12", taskType:"ctw", title:"Healthy sleep", level:"med", text:"Scientists have shown that regular [sleep|3] plays a vital role in [memory|3]. During deep rest, the brain [organizes|4] what we learned during the [day|1]. People who sleep too little often struggle to [concentrate|6] and feel more [anxious|3]. A steady bedtime routine can [improve|4] both mood and health." },
    { id:"f1ctw13", taskType:"ctw", title:"Ocean plastic", level:"med", text:"Every year, millions of tons of plastic reach the [ocean|3]. Much of this waste never [disappears|4]; instead it breaks into tiny [particles|4]. These pieces can harm fish and eventually enter the human [diet|2]. Reducing single-use packaging is one practical [solution|4] that communities can [adopt|3] quickly." },
    { id:"f1ctw14", taskType:"ctw", title:"Remote work", level:"med", text:"Working from home has become far more [common|4] in recent years. Many employees enjoy the [flexible|4] hours and the shorter [commute|4]. However, some find it hard to stay [motivated|5] without colleagues nearby. Companies now experiment with [hybrid|3] schedules to balance [freedom|4] and teamwork." },
    { id:"f1ctw15", taskType:"ctw", title:"Volcano basics", level:"med", text:"A volcano forms when hot [molten|4] rock rises toward the surface of the [planet|4]. Pressure builds until gas and lava finally [escape|3] through an opening. Some eruptions are gentle, while others are [violent|4] and dangerous. Scientists monitor these mountains to protect nearby [populations|4] from harm." },
    { id:"f1ctw16", taskType:"ctw", title:"The honey bee", level:"med", text:"Honey bees are essential to modern [agriculture|4] because they [pollinate|5] countless crops. Without them, many fruits and vegetables would become [scarce|3] and expensive. In recent decades, bee colonies have [declined|4] in several countries. Researchers believe that pesticides and disease may be [responsible|4] for this worrying trend." },
    { id:"f1ctw17", taskType:"ctw", title:"Ancient roads", level:"med", text:"The Romans built an enormous network of [roads|3] across their vast [empire|3]. These routes allowed armies to move [quickly|4] and merchants to trade [goods|3]. Engineers designed careful [drainage|5] so the surfaces would not flood. Many of these ancient paths still [survive|3] beneath modern streets today." },
    { id:"f1ctw18", taskType:"ctw", title:"Renewable energy", level:"med", text:"Solar and wind power are becoming increasingly [important|4] sources of clean [energy|3]. Unlike coal, they release almost no [carbon|4] when they generate electricity. The main challenge is storing power for times when the wind is [calm|3]. Better batteries could make these systems far more [reliable|4] in the future." },
    { id:"f1ctw19", taskType:"ctw", title:"Reading habits", level:"med", text:"Regular reading can noticeably expand a person's [vocabulary|5] and general [knowledge|4]. Fiction, in particular, may improve our ability to understand the [emotions|4] of others. Some studies suggest that readers are more [patient|4] and thoughtful listeners. Building a daily habit is easier when the material feels [enjoyable|4]." },
    { id:"f1ctw20", taskType:"ctw", title:"Mountain weather", level:"med", text:"Weather in the mountains can change with surprising [speed|3]. A sunny morning may turn into a cold [storm|3] within hours. Experienced hikers always carry extra [clothing|5] and enough [water|3]. Checking the forecast before you leave is a simple [precaution|4] that can prevent serious [trouble|4]." },
    { id:"f1ctw21", taskType:"ctw", title:"Photosynthesis", level:"hard", text:"Through photosynthesis, green plants [transform|5] sunlight into chemical [energy|3]. Specialized structures called chloroplasts [absorb|3] light and drive a series of complex [reactions|4]. The process releases oxygen as a valuable [byproduct|4] that most living creatures [require|4]. Understanding this mechanism is fundamental to modern [biology|4]." },
    { id:"f1ctw22", taskType:"ctw", title:"Economic inflation", level:"hard", text:"Inflation describes a general and sustained rise in the [prices|4] of goods and [services|4]. When it accelerates, the purchasing power of ordinary [currency|4] gradually erodes. Central banks often respond by raising interest [rates|3] to cool [demand|4]. Managing this balance requires considerable [judgment|4] and reliable economic [indicators|4]." },
    { id:"f1ctw23", taskType:"ctw", title:"The immune system", level:"hard", text:"The human immune system defends the body against a constant stream of [pathogens|4]. Specialized white blood cells can [recognize|4] harmful invaders and neutralize them [efficiently|4]. Vaccines exploit this ability by training the body to [anticipate|4] a specific threat. This remarkable [defense|4] usually operates without our conscious [awareness|4]." },
    { id:"f1ctw24", taskType:"ctw", title:"Democratic institutions", level:"hard", text:"Stable democracies rely on independent institutions to [constrain|5] the exercise of political [authority|4]. Courts, a free press, and honest elections together [preserve|4] the rule of law. When these safeguards weaken, corruption tends to [flourish|4] and public trust [deteriorates|4]. Citizens therefore share a lasting [responsibility|4] to defend such structures." },
    { id:"f1ctw25", taskType:"ctw", title:"Quantum computing", level:"hard", text:"Quantum computers exploit the strange behavior of matter at the smallest [scales|4]. Instead of ordinary bits, they manipulate fragile units known as [qubits|4]. Because these states are easily [disturbed|4], engineers must isolate the machine from every [vibration|4]. If perfected, the technology could [revolutionize|4] fields from chemistry to [cryptography|5]." },
    { id:"f1ctw26", taskType:"ctw", title:"Glacial retreat", level:"hard", text:"Across the polar regions, ancient glaciers are [retreating|4] at an alarming [pace|3]. As temperatures climb, enormous volumes of ice gradually [dissolve|4] into the sea. This meltwater contributes directly to rising ocean [levels|4] worldwide. Scientists warn that coastal cities may face frequent [flooding|4] within a few [decades|4]." },
    { id:"f1ctw27", taskType:"ctw", title:"Cognitive bias", level:"hard", text:"Human reasoning is often distorted by subtle [cognitive|4] biases we rarely [notice|4]. For instance, people tend to favor information that [confirms|4] their existing beliefs. Recognizing these tendencies is the first step toward more [rational|4] decisions. Careful, deliberate thinking can partly [compensate|4] for our natural [limitations|4]." },
    { id:"f1ctw28", taskType:"ctw", title:"The nitrogen cycle", level:"hard", text:"Nitrogen circulates continuously among the [atmosphere|4], soil, and living [organisms|4]. Certain bacteria convert inert nitrogen gas into compounds that plants can [absorb|4]. Animals then obtain this essential element by [consuming|4] those plants. When organisms die, decomposition eventually [returns|4] the nitrogen to the surrounding [environment|4]." },
    { id:"f1ctw29", taskType:"ctw", title:"Architectural acoustics", level:"hard", text:"Designing a concert hall demands a deep understanding of how sound [behaves|4] within an enclosed [space|3]. Architects manipulate materials and shapes to control [reflections|4] and unwanted echoes. Even small adjustments can dramatically alter the perceived [clarity|4] of the music. Achieving balanced [resonance|4] remains one of the field's greatest [challenges|4]." },
    { id:"f1ctw30", taskType:"ctw", title:"Evolutionary adaptation", level:"hard", text:"Over countless generations, species gradually [adapt|4] to the pressures of their [environment|4]. Individuals with advantageous traits are more likely to [reproduce|4] and pass them on. This slow, cumulative process can eventually [transform|4] the anatomy of an entire [population|4]. The resulting diversity of life reflects billions of years of relentless [selection|4]." }
  ],
  daily: [
    {
      id:"f1dl01",
      taskType:"daily",
      title:"Notice",
      level:"easy",
      text:"POOL CLOSED FOR CLEANING\n\nThe community swimming pool will be closed on Monday and Tuesday next week for its yearly cleaning. It will open again on Wednesday at 7 a.m. During the closure, members may use the pool at the North Park center for free. Just show your membership card at the front desk. We are sorry for any trouble, and we thank you for your patience. If you have questions, please call the office at 555-0192 between 9 a.m. and 5 p.m.",
      q: [
        { stem:"What is the main purpose of this notice?", opts:["To announce a new pool at North Park","To inform members that the pool will close for cleaning","To raise the price of pool membership","To invite members to a swimming class"], a:1 },
        { stem:"When will the community pool open again?", opts:["Monday morning","Tuesday evening","Wednesday at 7 a.m.","Friday at 9 a.m."], a:2 },
        { stem:"What must members do to use the North Park pool?", opts:["Pay a small fee","Call the office first","Show their membership card","Sign a new form"], a:2 }
      ]
    },
    {
      id:"f1dl02",
      taskType:"daily",
      title:"Email",
      level:"med",
      text:"From: Ms. Alvarez, Project Coordinator\nSubject: Change to Friday's team meeting\n\nHi everyone,\n\nI'm writing to let you know that Friday's meeting has been moved from 10 a.m. to 2 p.m. because the main conference room is being used for a training session in the morning. We will now meet in Room B on the second floor instead of our usual space. Please bring a printed copy of your progress report, since the projector in Room B is currently broken. If 2 p.m. does not work for you, reply to me by Thursday noon and I will try to arrange a short separate call. Thanks for being flexible.\n\nBest,\nMs. Alvarez",
      q: [
        { stem:"Why is Ms. Alvarez sending this email?", opts:["To cancel Friday's meeting completely","To announce changes to the meeting time and place","To ask staff to write a new report","To introduce a new team member"], a:1 },
        { stem:"Why should staff bring a printed report?", opts:["The projector in Room B does not work","There is no computer in the building","Printed reports are required by company rules","The meeting will be held outdoors"], a:0 },
        { stem:"What should someone do if 2 p.m. does not suit them?", opts:["Skip the meeting without telling anyone","Reply to Ms. Alvarez by Thursday noon","Wait until Friday to explain","Ask a coworker to attend instead"], a:1 }
      ]
    },
    {
      id:"f1dl03",
      taskType:"daily",
      title:"Post",
      level:"hard",
      text:"Forum post: Anyone else tried the new 'silent hours' policy?\n\nMy office recently introduced two 'silent hours' every afternoon, when messaging apps are muted and no meetings can be scheduled. I was skeptical at first, honestly. I assumed I would just fall behind on replies and feel more stressed. Yet after three weeks, the opposite happened. Because I'm no longer interrupted every few minutes, I finish focused tasks far more quickly, and I actually leave on time. The downside is that urgent questions occasionally wait longer than they should, so we've agreed on a phone number for genuine emergencies. Overall I'd recommend at least testing it. Curious whether it works in larger teams too.",
      q: [
        { stem:"What is the writer's main point in this post?", opts:["Silent hours ruined the office schedule","The silent hours policy turned out better than expected","Meetings should never be muted","The writer wants to quit the job"], a:1 },
        { stem:"What did the writer expect before trying the policy?", opts:["That it would help immediately","That they would fall behind and feel more stressed","That coworkers would refuse to join","That management would cancel it quickly"], a:1 },
        { stem:"How does the team handle truly urgent questions during silent hours?", opts:["They ignore them until the next day","They hold an extra meeting","They use an agreed phone number for emergencies","They send emails marked important"], a:2 }
      ]
    }
  ],
  academic: [
    {
      id:"f1ap01",
      taskType:"academic",
      title:"The Origins of Coffee",
      level:"med",
      text:"Few beverages have shaped daily life as widely as coffee, yet its origins are surprisingly humble. According to a popular legend, an Ethiopian goat herder noticed that his animals became unusually lively after eating the bright red berries of a certain shrub. Curious, he tried the berries himself and felt a similar burst of energy. While the story is almost certainly a later invention, it does capture a genuine truth: the coffee plant is native to the highlands of northeastern Africa, where people first learned to use it.\n\nFrom Africa, coffee spread across the Red Sea to the Arabian Peninsula, where it was cultivated systematically for the first time. By the fifteenth century, coffee was being roasted and brewed in a manner we would recognize today. The city of Mocha, in present-day Yemen, became a major center of trade, and its name still lingers in modern coffee vocabulary. Coffeehouses soon appeared throughout the region, functioning as lively spaces for conversation, music, and the exchange of news.\n\nWhen coffee finally reached Europe in the seventeenth century, it provoked both enthusiasm and suspicion. Some critics distrusted the dark, foreign drink, but its popularity proved unstoppable. European coffeehouses became known as centers of debate and business, where merchants, writers, and scientists gathered to argue and share ideas. In this way, a plant once chewed on an African hillside helped fuel some of the intellectual currents of the modern world.",
      q: [
        { stem:"What is the main idea of the passage?", opts:["Coffee is unhealthy and was once banned","Coffee spread from Africa across the world and influenced social life","The goat herder legend is completely true","European coffeehouses were mainly for the wealthy"], a:1 },
        { stem:"According to the passage, where is the coffee plant originally native to?", opts:["The Arabian Peninsula","The highlands of northeastern Africa","Southern Europe","The city of Mocha in Yemen"], a:1 },
        { stem:"The word \"lingers\" in the second paragraph is closest in meaning to", opts:["remains","disappears","weakens","competes"], a:0 },
        { stem:"What can be inferred about the goat herder legend?", opts:["It is the only record of coffee's discovery","It is likely a later invention but reflects a real truth","It was written down in the fifteenth century","It proves goats cannot digest berries"], a:1 },
        { stem:"According to the passage, what role did European coffeehouses play?", opts:["They served only as quiet resting places","They were centers of debate and business","They were used mainly for religious ceremonies","They replaced all local markets"], a:1 }
      ]
    },
    {
      id:"f1ap02",
      taskType:"academic",
      title:"How Bird Migration Is Guided",
      level:"hard",
      text:"Each year, billions of birds undertake journeys of astonishing length, some traveling from one hemisphere to the other and back again. For centuries, the mechanisms behind these migrations remained a profound mystery. How could a small songbird, with no map and no prior experience, locate a distant wintering ground with such precision? Modern research has revealed that birds rely not on a single sense but on an integrated set of cues that together form a remarkably robust navigation system.\n\nOne of the most important of these cues is the sun. Many species use the position of the sun, combined with an internal clock, to maintain a consistent heading throughout the day. At night, migrating birds instead orient themselves by the stars, learning as juveniles to recognize the fixed point around which the night sky appears to rotate. Perhaps most striking is the ability of certain birds to detect the Earth's magnetic field. Specialized cells, possibly located in the eye or beak, allow them to perceive magnetic direction and even, in some cases, magnetic intensity, which varies predictably across the planet's surface.\n\nCrucially, these systems do not operate in isolation. A bird flying beneath a cloudy night sky may switch from stellar cues to its magnetic sense, then recalibrate against the setting sun at dusk. This redundancy makes migration resilient to the failure of any single cue. Yet the system is not invulnerable. Artificial light, tall illuminated buildings, and shifting climate patterns increasingly disrupt these ancient routes, drawing conservationists' attention to the fragile navigational abilities that sustain migratory life.",
      q: [
        { stem:"What is the main idea of the passage?", opts:["Birds migrate only because of warmer weather","Birds navigate using several complementary cues that work together","The magnetic sense is the only thing birds use","Migration has been fully understood for centuries"], a:1 },
        { stem:"According to the passage, how do migrating birds orient themselves at night?", opts:["By following the sun's position","By recognizing the fixed point around which the stars rotate","By listening to other birds","By memorizing landmarks on the ground"], a:1 },
        { stem:"The word \"robust\" in the first paragraph is closest in meaning to", opts:["fragile","strong and reliable","confusing","temporary"], a:1 },
        { stem:"Why does the passage emphasize that the cues do not operate in isolation?", opts:["To show that birds only use one cue at a time","To explain that redundancy makes navigation resilient","To prove the sun is unimportant","To argue that birds never make mistakes"], a:1 },
        { stem:"According to the passage, what increasingly disrupts bird migration?", opts:["Artificial light, illuminated buildings, and climate change","A lack of food in the summer","Too many stars in the sky","The Earth's magnetic field disappearing"], a:0 }
      ]
    }
  ]
};
