window.FORM2_READING = {
  ctw: [
    { id: "f2ctw01", taskType: "ctw", title: "Lighthouses", level: "easy", text: "A lighthouse is a tall [tower|3] built near the [coast|2] to guide ships at [night|2]. Its bright [light|3] warns sailors about dangerous rocks so their boats stay [safe|2] and reach the [harbor|3]." },
    { id: "f2ctw02", taskType: "ctw", title: "Fountain Pens", level: "easy", text: "A fountain pen holds liquid [ink|1] inside a small [tank|2]. When you [write|2], the ink flows down to a metal [tip|1] and leaves a smooth [line|2] on the [paper|3], which many people find [elegant|3]." },
    { id: "f2ctw03", taskType: "ctw", title: "Kites", level: "easy", text: "A kite is a light [frame|2] covered with cloth or [paper|2] that flies in the [wind|2]. You hold a long [string|3] and run until the kite [rises|2] high into the open [sky|1]." },
    { id: "f2ctw04", taskType: "ctw", title: "Sundials", level: "easy", text: "A sundial tells the [time|2] by using [sunlight|3]. A raised part casts a dark [shadow|3] onto a flat [plate|2], and as the sun [moves|2], the shadow points to different [hours|2] marked on the [surface|3]." },
    { id: "f2ctw05", taskType: "ctw", title: "Umbrellas", level: "easy", text: "An umbrella keeps you dry when it starts to [rain|2]. You push it [open|2], and the round [cover|3] blocks the falling [water|2], so your [clothes|3] stay dry and you can keep [walking|3] to work." },
    { id: "f2ctw06", taskType: "ctw", title: "Windmills", level: "easy", text: "A windmill has large [blades|3] that turn when the [wind|2] blows. This spinning motion can grind grain into [flour|2] or pump [water|2] from deep under the [ground|3], helping farmers on the [farm|2]." },
    { id: "f2ctw07", taskType: "ctw", title: "Ferries", level: "easy", text: "A ferry is a wide [boat|2] that carries people and cars across a [river|2] or bay. Passengers drive on board, the ferry [crosses|3] the water, and then everyone [drives|2] off on the other [side|2] to continue their [journey|3]." },
    { id: "f2ctw08", taskType: "ctw", title: "Home Gardens", level: "easy", text: "Many families grow a small [garden|3] behind their [house|2]. They plant tiny [seeds|3] in the soil, give them [water|2] and sunlight, and after a few [weeks|2] fresh vegetables begin to [grow|2]." },
    { id: "f2ctw09", taskType: "ctw", title: "Bicycles", level: "easy", text: "A bicycle is a simple [machine|3] with two round [wheels|3]. You sit on the [seat|2], push the [pedals|3] with your feet, and steer with the [handle|3] to travel quickly without using any [fuel|2]." },
    { id: "f2ctw10", taskType: "ctw", title: "Bridges", level: "easy", text: "A bridge lets people cross over a [river|2] or busy [road|2]. Engineers build strong [columns|3] to hold the heavy [weight|3], and cars can then drive safely from one [bank|2] to the other [side|2]." },
    { id: "f2ctw11", taskType: "ctw", title: "Papermaking", level: "med", text: "Papermaking begins by soaking plant [fibers|3] in water until they soften into a thick [pulp|2]. A worker spreads this mixture across a fine [screen|3], lets the water [drain|3] away, and then presses the wet sheet to remove any remaining [moisture|4]. Once it has fully [dried|2], the flat sheet becomes a usable piece of [paper|2]." },
    { id: "f2ctw12", taskType: "ctw", title: "Glassblowing", level: "med", text: "Glassblowing is an ancient [craft|3] in which a worker gathers molten [glass|3] onto the end of a hollow [pipe|2]. By blowing gently through the tube, the artisan [shapes|3] the soft material into a hollow [vessel|3], then cools it slowly so the finished object does not [crack|3] as it hardens." },
    { id: "f2ctw13", taskType: "ctw", title: "Terraced Farming", level: "med", text: "On steep mountain [slopes|3], farmers cut the land into flat [steps|3] called terraces. These level platforms trap rain and prevent [erosion|4], allowing crops such as [rice|2] to grow where the ground would otherwise be too [narrow|3]. The method demands great [effort|3] but greatly increases the usable [area|2]." },
    { id: "f2ctw14", taskType: "ctw", title: "Cheese Caves", level: "med", text: "Some cheeses develop their flavor while resting inside cool [caves|3]. The steady [temperature|4] and damp air help friendly [bacteria|4] and mold to grow slowly on the [surface|3]. Over many [months|3], these tiny organisms change the texture and create the sharp [taste|2] that customers [enjoy|3]." },
    { id: "f2ctw15", taskType: "ctw", title: "Salt Harvesting", level: "med", text: "Along shallow coastal [ponds|3], workers guide seawater into wide, flat [basins|3]. As the sun and wind cause the water to [evaporate|4], a thin crust of white [salt|2] slowly forms on the bottom. Laborers then [rake|2] the crystals into small [piles|3] and leave them to [dry|2] before packing." },
    { id: "f2ctw16", taskType: "ctw", title: "Braille", level: "med", text: "Braille is a system of raised [dots|2] that allows blind readers to read with their [fingers|3]. Each small [pattern|3] of bumps stands for a single letter or [number|3]. By moving a hand across the [page|2], a reader can quickly [sense|3] the shapes and understand the written [message|3]." },
    { id: "f2ctw17", taskType: "ctw", title: "Carrier Pigeons", level: "med", text: "Long before telephones, people sent urgent news using carrier [pigeons|3]. A short [message|3] was rolled up and tied to the bird's [leg|1]. Released far from home, the pigeon used its remarkable sense of [direction|4] to fly back to its own [loft|2], delivering the note faster than a human [rider|3] could travel." },
    { id: "f2ctw18", taskType: "ctw", title: "Ice Harvesting", level: "med", text: "Before electric [freezers|3] existed, workers harvested ice from frozen [lakes|3] in winter. Using large saws, they cut the thick sheet into heavy [blocks|3], which were dragged ashore and stored in insulated [houses|3] packed with [sawdust|3]. The ice stayed [frozen|3] for months and was sold during the warm [summer|3]." },
    { id: "f2ctw19", taskType: "ctw", title: "The Abacus", level: "med", text: "The abacus is an ancient counting [tool|2] made of beads that slide along thin [rods|2]. By moving the beads up and [down|2], a skilled user can add, subtract, and even [multiply|4] large numbers with surprising [speed|3]. Long before the electronic [calculator|4], merchants relied on it to track their daily [trade|3]." },
    { id: "f2ctw20", taskType: "ctw", title: "Saffron", level: "med", text: "Saffron is one of the world's most expensive [spices|3], gathered from the delicate purple [flowers|3] of a small crocus. Each blossom contains only three red [threads|3], which must be picked by [hand|2] at dawn. Because thousands of flowers are needed for a single [gram|2], the price remains extremely [high|2], and buyers value its rich [color|3]." },
    { id: "f2ctw21", taskType: "ctw", title: "Glowing Fungi", level: "hard", text: "In certain damp forests, a few species of [fungi|3] produce a faint green [glow|2] in the darkness. This natural light results from a chemical [reaction|4] inside their living [tissue|3], a phenomenon scientists call bioluminescence. Researchers suspect the eerie [radiance|4] may attract insects that help [disperse|4] the mushroom's tiny [spores|3] across the forest floor." },
    { id: "f2ctw22", taskType: "ctw", title: "Map Projections", level: "hard", text: "Because the Earth is a [sphere|3], mapmakers face an unavoidable [problem|4] when they flatten it onto a page. Every projection must [distort|4] some feature, stretching the size of certain [regions|3] while shrinking others. A navigator therefore chooses a projection whose particular [accuracy|4] suits the intended [purpose|3], accepting the trade-offs that each method inevitably [creates|3]." },
    { id: "f2ctw23", taskType: "ctw", title: "Peat Bogs", level: "hard", text: "Peat bogs are waterlogged wetlands where dead plants accumulate faster than they can [decay|3]. The cold, acidic, oxygen-poor [conditions|4] slow the work of [bacteria|3], so partially rotted vegetation piles up over [centuries|4] into a dense brown [layer|3]. Remarkably, these bogs [preserve|4] ancient pollen and even human remains, offering scientists a rare window into the distant [past|2]." },
    { id: "f2ctw24", taskType: "ctw", title: "Lichen Partnership", level: "hard", text: "A lichen is not a single organism but a close [partnership|4] between a fungus and an [alga|2]. The fungus supplies structure and [moisture|3], while the alga uses sunlight to manufacture [sugars|3] that feed them both. This mutual [arrangement|4] lets lichens survive on bare [rock|2] where few other living things could ever [establish|4] themselves." },
    { id: "f2ctw25", taskType: "ctw", title: "Tidal Mills", level: "hard", text: "Long before steam power, coastal communities harnessed the rising and falling [tide|2] to grind grain. A mill pond filled as the sea [advanced|4], and a gate trapped the water at high [level|3]. When the tide [retreated|4], the stored water was released through a [wheel|3], turning heavy stones that crushed the [grain|3] into flour with no other source of [energy|3]." },
    { id: "f2ctw26", taskType: "ctw", title: "Semaphore Towers", level: "hard", text: "In the years before electric wires, some nations built chains of hilltop [towers|3] to relay messages across great [distances|4]. Each station carried movable wooden [arms|2] whose positions represented letters of a coded [alphabet|4]. An operator read the neighboring signal through a [telescope|4] and repeated it, allowing news to travel hundreds of miles in a single [hour|2], far faster than a galloping [horse|3]." },
    { id: "f2ctw27", taskType: "ctw", title: "Cork Oak", level: "hard", text: "The cork oak is an unusual tree whose thick outer [bark|2] can be stripped without harming the trunk. Harvesters carefully peel away the spongy [layer|3] every nine years, and the tree gradually [regenerates|4] a fresh coat. This renewable [material|4] is light, waterproof, and [elastic|3], making it ideal for bottle stoppers and floor [tiles|3] alike." },
    { id: "f2ctw28", taskType: "ctw", title: "Mangrove Forests", level: "hard", text: "Mangroves are salt-tolerant trees that thrive where rivers meet the [sea|2]. Their tangled arching [roots|3] rise above the muddy water, trapping sediment and shielding the [coast|3] from destructive storm [waves|3]. The sheltered maze also serves as a [nursery|4] for young fish, so protecting these forests benefits both wildlife and nearby human [communities|4]." },
    { id: "f2ctw29", taskType: "ctw", title: "Seed Vaults", level: "hard", text: "Deep inside a frozen mountain, a secure [vault|3] stores hundreds of thousands of plant [seeds|3] from around the world. Kept at a constant freezing [temperature|4], the samples can remain [viable|3] for centuries. Should a war or natural [disaster|4] wipe out a crop, farmers could withdraw duplicates and restore the lost [variety|4], safeguarding future food [security|4]." },
    { id: "f2ctw30", taskType: "ctw", title: "Windcatchers", level: "hard", text: "In hot desert cities, traditional buildings often feature a tall [tower|3] designed to cool the rooms below. Known as a windcatcher, this clever [structure|4] captures passing breezes and funnels the cooler air [downward|4]. As warm air rises and [escapes|3], a gentle [current|4] circulates without any electricity, providing natural [comfort|3] that predates the modern air [conditioner|4]." }
  ],
  daily: [
    {
      id: "f2dl01",
      taskType: "daily",
      title: "Notice",
      level: "easy",
      text: "NOTICE: Riverside Community Library\n\nStarting next Monday, the library will open one hour earlier, at 8:00 a.m., on weekdays. We are adding this early hour so that students can study before school and commuters can borrow books on their way to work.\n\nThe children's reading corner has also moved to the second floor, next to the large windows. Please note that the ground-floor meeting room will be closed for painting until the end of the month.\n\nRemember that borrowed books may be renewed online through our website. If you have questions, please speak to a staff member at the front desk. Thank you for helping us keep the library quiet and tidy.",
      q: [
        { stem: "What change begins next Monday?", opts: ["The library will open one hour earlier on weekdays.", "The library will close one hour later each day.", "The library will open on weekends only.", "The library will reduce its total opening hours."], a: 0 },
        { stem: "Where has the children's reading corner moved?", opts: ["To the ground floor near the entrance.", "To the second floor, next to the large windows.", "To the closed meeting room.", "To the front desk area."], a: 1 },
        { stem: "Why is the ground-floor meeting room closed?", opts: ["Because it is being painted.", "Because of a large staff meeting.", "Because it has run out of books.", "Because it has moved upstairs."], a: 0 }
      ]
    },
    {
      id: "f2dl02",
      taskType: "daily",
      title: "Email",
      level: "med",
      text: "Subject: Your Pottery Workshop Registration\n\nDear Ms. Alvarez,\n\nThank you for signing up for our Saturday pottery workshop. Your place is confirmed for July 25 at 10:00 a.m. in Studio B.\n\nPlease arrive fifteen minutes early and wear old clothes, as clay can stain fabric. All tools are provided, so bring only a water bottle. The session lasts three hours, including a short tea break.\n\nBecause the kiln holds a limited number of pieces, each participant may make no more than two bowls. Your finished work will be ready to collect two weeks later, after it has been glazed and fired.\n\nIf you must cancel, please tell us at least 48 hours in advance.\n\nWarm regards,\nThe Clayhouse Studio Team",
      q: [
        { stem: "What should Ms. Alvarez bring to the workshop?", opts: ["Her own clay and tools.", "Only a water bottle.", "A set of old clothes to give away.", "Two finished bowls."], a: 1 },
        { stem: "Why are participants limited to two bowls each?", opts: ["Because clay is very expensive.", "Because the kiln holds only a limited number of pieces.", "Because the session is too short.", "Because glaze is in short supply."], a: 1 },
        { stem: "When can Ms. Alvarez collect her finished work?", opts: ["Immediately after the session ends.", "The following day.", "Two weeks later, after glazing and firing.", "Within 48 hours of cancelling."], a: 2 }
      ]
    },
    {
      id: "f2dl03",
      taskType: "daily",
      title: "Post",
      level: "hard",
      text: "Trail Update: Cedar Ridge Loop\n\nI hiked the Cedar Ridge Loop yesterday and want to share a few honest notes for anyone planning to go this weekend. The lower section is in excellent shape, but the upper switchbacks are still muddy from last week's rain, so waterproof boots are essential rather than optional.\n\nThe wooden bridge near the waterfall has been repaired, which is great news, yet the sign pointing to the summit has fallen down. Turn left at the large split boulder instead; the unmarked path is easy to miss.\n\nOne warning: cell coverage disappears completely past the ridge, so download your map beforehand. I would not attempt the full loop after heavy rain, but on a dry day it remains one of the most rewarding hikes in the region.",
      q: [
        { stem: "What does the writer imply about waterproof boots?", opts: ["They are unnecessary in any weather.", "They are strongly recommended because the upper trail is muddy.", "They should be removed before crossing the bridge.", "They are provided at the trailhead."], a: 1 },
        { stem: "Why does the writer mention the fallen summit sign?", opts: ["To warn that hikers must turn left at the split boulder to stay on course.", "To complain about the repair of the wooden bridge.", "To explain why the waterfall area is closed.", "To recommend buying a new sign."], a: 0 },
        { stem: "What can be inferred about hiking the full loop after heavy rain?", opts: ["It is the writer's favorite condition for the hike.", "The writer would not recommend attempting it.", "It offers much better cell coverage.", "It makes the repaired bridge collapse."], a: 1 }
      ]
    }
  ],
  academic: [
    {
      id: "f2ap01",
      taskType: "academic",
      title: "The Urban Heat Island",
      level: "med",
      text: "Anyone who has walked through a city on a summer evening may have noticed that the streets feel warmer than the surrounding countryside. Scientists call this effect the urban heat island. Cities tend to be several degrees hotter than nearby rural areas, and the difference is often greatest at night. The cause lies in the materials from which cities are built. Concrete, asphalt, and brick absorb heat from the sun throughout the day and release it slowly after dark, whereas soil and vegetation cool down more quickly once the sun sets.\n\nSeveral other factors intensify the effect. Tall buildings trap heat within narrow streets, reducing the flow of cooling breezes. The scarcity of trees means less shade and less evaporation, a natural process that would otherwise lower temperatures. Meanwhile, cars, air conditioners, and factories continuously pour additional warmth into the air. Together these influences can make a large city noticeably uncomfortable during a heat wave, and they place extra strain on the health of elderly residents.\n\nFortunately, planners have discovered practical remedies. Painting rooftops white reflects sunlight instead of absorbing it. Planting trees along avenues restores shade and moisture, and creating parks introduces patches of cooler green space. Some cities now require new buildings to include gardens on their roofs. Such measures cannot eliminate the heat island entirely, but they can soften its harshest effects and make dense urban life more bearable.",
      q: [
        { stem: "What is the passage mainly about?", opts: ["Why cities are warmer than rural areas and how the effect can be reduced.", "How concrete and asphalt are manufactured for modern buildings.", "The specific health problems faced by elderly city residents.", "The best way to design a large public park."], a: 0 },
        { stem: "According to the passage, why do cities cool down more slowly at night than the countryside?", opts: ["Because rural soil absorbs far more sunlight.", "Because urban materials such as concrete release stored heat slowly.", "Because cities generally contain more trees.", "Because breezes flow faster between tall buildings."], a: 1 },
        { stem: "Which of the following is NOT mentioned as a factor that intensifies the urban heat island?", opts: ["Tall buildings that block cooling breezes.", "A shortage of trees.", "Heat from cars and air conditioners.", "Frequent heavy rainfall in cities."], a: 3 },
        { stem: "The word 'scarcity' in the passage is closest in meaning to", opts: ["lack", "beauty", "growth", "variety"], a: 0 },
        { stem: "What can be inferred about painting rooftops white?", opts: ["It causes buildings to absorb even more heat.", "It helps keep buildings and the surrounding city cooler.", "It is now legally required in every city.", "It completely replaces the need for trees."], a: 1 }
      ]
    },
    {
      id: "f2ap02",
      taskType: "academic",
      title: "The Longitude Problem",
      level: "hard",
      text: "For centuries, sailors could determine their latitude, their position north or south, with reasonable ease by measuring the height of the sun or the North Star above the horizon. Longitude, the east-west position, proved far more elusive. Without a reliable way to calculate it, ships frequently miscalculated their location, ran aground, or wasted weeks searching for their destination. The problem was so serious that several governments offered enormous financial rewards to anyone who could solve it.\n\nThe key insight was that longitude is fundamentally a question of time. Because the Earth rotates once every twenty-four hours, each hour of difference between local time and the time at a fixed reference point corresponds to a predictable distance east or west. A navigator who knew both the local time, found from the position of the sun, and the exact time at the home port could therefore compute the longitude. The obstacle was practical: no clock of the era could keep accurate time aboard a rocking ship, where changing temperatures and constant motion ruined delicate mechanisms.\n\nIn the eighteenth century, a self-taught English carpenter named John Harrison devoted decades to building a clock that could withstand these conditions. His marine chronometer used novel materials and clever mechanisms that compensated for temperature and movement. After repeated trials at sea, the device proved astonishingly accurate, losing only a few seconds on long voyages. Although Harrison struggled for years to receive the promised reward, his invention transformed navigation and saved countless lives, demonstrating that a mechanical solution could triumph where astronomers had long searched the skies.",
      q: [
        { stem: "What is the main idea of the passage?", opts: ["How the difficult problem of measuring longitude was finally solved by an accurate seagoing clock.", "How sailors first learned to measure latitude using the North Star.", "Why governments should always offer financial rewards for new inventions.", "How the rotation of the Earth causes day and night."], a: 0 },
        { stem: "Why was measuring longitude connected to timekeeping?", opts: ["Because clocks were the only instruments available on ships.", "Because the time difference from a fixed reference point corresponds to east-west distance.", "Because sailors needed to know exactly when to sleep.", "Because latitude also depended entirely on clocks."], a: 1 },
        { stem: "According to the passage, why did ordinary clocks fail at sea?", opts: ["They were far too expensive for sailors to buy.", "Temperature changes and constant motion disrupted their mechanisms.", "Sailors were never taught how to read them.", "They could only be used to measure latitude."], a: 1 },
        { stem: "The word 'elusive' in the first paragraph is closest in meaning to", opts: ["hard to achieve", "easy to see", "widely known", "brightly lit"], a: 0 },
        { stem: "What can be inferred about John Harrison from the passage?", opts: ["He was already a famous astronomer of his era.", "He gave up before ever completing his clock.", "He showed great persistence despite difficulty in being rewarded.", "He invented the original method of measuring latitude."], a: 2 }
      ]
    }
  ]
};
