window.FORM3_READING = {
  ctw: [
    { id:"f3ctw01", taskType:"ctw", title:"The corner bakery", level:"easy", text:"A small [bakery|3] sits on the corner near my [house|3]. Every morning the baker fills the shelves with fresh [bread|3] and warm [rolls|3]. The smell drifts down the [street|3] and makes me feel [hungry|4]. I often stop there to buy a [treat|3] on my way to work." },
    { id:"f3ctw02", taskType:"ctw", title:"Feeding the ducks", level:"easy", text:"On Sunday we walk to the [pond|2] to feed the [ducks|3]. My little brother brings a bag of old [bread|3]. The birds swim over quickly when they [see|1] us. We are careful not to give them too [much|2], because that is not [good|2] for them. Watching them splash is always [fun|1]." },
    { id:"f3ctw03", taskType:"ctw", title:"A day at the beach", level:"easy", text:"We spent the whole [day|1] at the beach last [summer|3]. The sand was warm under our bare [feet|2], and the water felt [cool|2]. My sister built a tall [castle|3] near the waves. We ate lunch under a big [umbrella|4] and watched the [boats|3] far out at sea." },
    { id:"f3ctw04", taskType:"ctw", title:"Riding a bicycle", level:"easy", text:"Learning to ride a [bicycle|4] takes a little [practice|4]. At first you may feel [afraid|3] of falling. Keep your eyes on the [road|2] ahead and hold the handlebars [firmly|4]. Once you find your [balance|4], riding becomes easy and [fun|1]." },
    { id:"f3ctw05", taskType:"ctw", title:"The old clock", level:"easy", text:"An old [clock|3] hangs in my grandfather's [hallway|4]. It has been in the family for many [years|3]. Every hour it makes a soft [sound|3] that fills the [house|3]. My grandfather winds it each [night|3] before he goes to [bed|2]. He says the clock is his oldest [friend|3]." },
    { id:"f3ctw06", taskType:"ctw", title:"Painting the fence", level:"easy", text:"Last weekend my father decided to [paint|3] the garden [fence|3]. We chose a bright shade of [white|3] to match the [house|3]. I helped by holding the [brush|3] steady while he opened the [can|2]. The work took all [afternoon|5], but the fence looked [new|1] when we finished." },
    { id:"f3ctw07", taskType:"ctw", title:"A picnic in the park", level:"easy", text:"We packed a basket and went for a [picnic|3] in the [park|2]. Mother made sandwiches, and I brought some [fruit|3]. We spread a large [blanket|4] under a shady [tree|2]. After eating, we played a quiet [game|2] and watched the clouds drift [slowly|4] across the sky." },
    { id:"f3ctw08", taskType:"ctw", title:"My grandmother's soup", level:"easy", text:"My grandmother makes the best vegetable [soup|2] in the world. She starts by cutting fresh [carrots|4] and [onions|3]. Then she adds them to a pot of boiling [water|3]. The kitchen soon fills with a wonderful [smell|3]. We all sit down to eat while the soup is still [warm|2]." },
    { id:"f3ctw09", taskType:"ctw", title:"The kite festival", level:"easy", text:"Every spring our town holds a colorful kite [festival|4]. Children and adults gather in the open [field|3]. They bring kites of every [shape|3] and color. When the [wind|2] is strong, the kites climb high into the [sky|2]. Everyone cheers when a kite reaches the very [top|2]." },
    { id:"f3ctw10", taskType:"ctw", title:"Waiting for the bus", level:"easy", text:"Each morning I wait for the [bus|2] at the corner near my [school|3]. Sometimes it arrives early, and sometimes it is a little [late|2]. I use the time to read a few [pages|3] of my book. When the bus finally [comes|3], I find a seat by the [window|3] and watch the town go by." },
    { id:"f3ctw11", taskType:"ctw", title:"Recycling glass", level:"med", text:"Recycling glass is one of the most [efficient|4] ways to save [energy|3]. Old bottles and jars can be [melted|4] and shaped into new [containers|5] again and again. Unlike some materials, glass does not lose its [quality|4] when it is reused. Communities that collect glass separately help reduce the [demand|3] for raw sand and lower factory [pollution|4]." },
    { id:"f3ctw12", taskType:"ctw", title:"The history of paper", level:"med", text:"Paper was first [invented|4] in ancient China nearly two thousand years [ago|2]. Early makers pressed together fibers from plants and old [cloth|3] to form thin [sheets|3]. This new material was far cheaper than the [surfaces|4] people had used before. Over many centuries, the knowledge of papermaking slowly [spread|3] westward and transformed how societies stored [information|4]." },
    { id:"f3ctw13", taskType:"ctw", title:"How muscles grow", level:"med", text:"When you exercise, tiny fibers inside your [muscles|4] develop small [tears|3]. Although this sounds harmful, it is a normal part of getting [stronger|4]. During rest, the body [repairs|4] these fibers and makes them thicker than [before|3]. This is why athletes need enough [rest|2] and good [nutrition|4] to improve their performance." },
    { id:"f3ctw14", taskType:"ctw", title:"Desert plants", level:"med", text:"Plants that live in the desert have developed clever ways to [survive|3] with very little [water|3]. Some store moisture inside thick, fleshy [leaves|3] or stems. Others grow long roots that reach deep [underground|5] to find hidden supplies. Their waxy surfaces reduce the amount of water lost to the dry [air|1]. These adaptations allow them to [endure|4] months without a single drop of [rain|2]." },
    { id:"f3ctw15", taskType:"ctw", title:"The invention of the telescope", level:"med", text:"The telescope changed how humans understood their place in the [universe|4]. Early versions, built in the seventeenth [century|4], used simple curved [lenses|3] to make distant objects appear [closer|3]. With this tool, astronomers discovered mountains on the moon and moons around other [planets|4]. These observations challenged old [beliefs|4] and encouraged a more scientific view of the [heavens|4]." },
    { id:"f3ctw16", taskType:"ctw", title:"River deltas", level:"med", text:"A river delta forms where a large river meets a calmer body of [water|3]. As the current slows, it drops the [sediment|4] it has carried for many [miles|3]. Over time these deposits build fertile land shaped like a fan or [triangle|4]. Deltas are often rich in [wildlife|4] and make excellent farmland. However, they can also [flood|3] easily during heavy storms." },
    { id:"f3ctw17", taskType:"ctw", title:"The role of forests", level:"med", text:"Forests play a crucial role in keeping our planet [healthy|4]. Their trees absorb carbon dioxide and release the oxygen that animals need to [breathe|4]. The dense roots hold the [soil|2] in place and prevent it from washing [away|2]. Forests also provide a home for countless [species|4] of insects, birds, and mammals. Protecting them is essential for a stable [climate|4]." },
    { id:"f3ctw18", taskType:"ctw", title:"Ancient Egyptian writing", level:"med", text:"The ancient Egyptians recorded their [history|4] using a system of picture symbols called [hieroglyphs|5]. Each sign could represent a sound, an object, or a whole [idea|2]. Scribes spent many years learning to read and [write|3] these complex marks. For centuries after the civilization declined, no one could [understand|5] them. The mystery was finally solved when scholars discovered a stone carved in several [languages|4]." },
    { id:"f3ctw19", taskType:"ctw", title:"The domestication of dogs", level:"med", text:"Dogs were the first animals that humans ever [tamed|3]. Thousands of years ago, wild wolves began to gather near human [camps|3] in search of food scraps. The friendliest animals were allowed to [stay|2], and over generations they grew gentler and more [loyal|3]. Eventually people bred them to help with hunting, guarding, and herding [livestock|4]. Today dogs remain one of our closest animal [companions|4]." },
    { id:"f3ctw20", taskType:"ctw", title:"Weather forecasting", level:"med", text:"Meteorologists use many tools to predict the [weather|4] several days [ahead|2]. Satellites high above the earth photograph the movement of large cloud [systems|4]. Ground stations measure temperature, humidity, and air [pressure|4] every hour. Powerful computers then combine this data to build detailed [models|3] of the atmosphere. Although forecasts have improved greatly, nature can still surprise even the best [experts|4]." },
    { id:"f3ctw21", taskType:"ctw", title:"Plate tectonics", level:"hard", text:"The theory of plate tectonics explains how the outer shell of the earth is broken into enormous moving [fragments|4]. These rigid plates drift slowly upon a layer of hotter, softer [rock|2] beneath them. Where two plates collide, immense pressure can push up towering mountain [ranges|3]. Elsewhere, plates pull apart and allow molten material to [rise|2] toward the surface. This constant motion continually [reshapes|4] the geography of our [planet|4]." },
    { id:"f3ctw22", taskType:"ctw", title:"The Doppler effect", level:"hard", text:"The Doppler effect describes how the observed frequency of a wave changes when its source is [moving|3]. As an ambulance approaches, its siren sounds higher because the sound waves are [compressed|4]. Once it passes, the pitch appears to [drop|2] as the waves stretch out behind it. Astronomers rely on the same [principle|4] to measure the motion of distant [galaxies|4]. Light from objects racing away from us shifts toward the red end of the [spectrum|4]." },
    { id:"f3ctw23", taskType:"ctw", title:"Market competition", level:"hard", text:"In a competitive market, rival firms constantly struggle to attract the same [customers|4]. To win their loyalty, companies may lower [prices|3], improve quality, or offer new [features|4]. This rivalry tends to benefit consumers, who enjoy greater choice and better [value|3]. When a single firm dominates, however, competition [weakens|4] and prices often [climb|3]. Economists therefore watch closely for signs that a market is becoming a [monopoly|4]." },
    { id:"f3ctw24", taskType:"ctw", title:"Genetic inheritance", level:"hard", text:"The traits that pass from parents to offspring are carried by units of information called [genes|3]. Each organism inherits two copies of every gene, one from each [parent|3]. Some versions are dominant and mask the effect of weaker, [recessive|4] ones. This is why a characteristic can seemingly disappear in one generation and then [reappear|4] in the next. By studying these patterns, scientists can predict the [probability|4] that a trait will be [inherited|4]." },
    { id:"f3ctw25", taskType:"ctw", title:"The Renaissance", level:"hard", text:"The Renaissance was a period of extraordinary cultural [rebirth|4] that began in Italy during the fourteenth century. Scholars rediscovered the writings of ancient Greece and [Rome|2] and studied them with fresh [enthusiasm|4]. Artists learned to depict the human body with remarkable [accuracy|4] and depth. Wealthy families spent fortunes to [sponsor|3] painters, architects, and thinkers. This flourishing of ideas gradually [transformed|4] European society." },
    { id:"f3ctw26", taskType:"ctw", title:"Ocean currents", level:"hard", text:"Vast currents circulate through the world's oceans, carrying warm and cold water across enormous [distances|4]. These flows are driven by differences in temperature, [salinity|4], and the rotation of the earth. By transporting heat from the equator toward the poles, currents strongly influence regional [climates|4]. A single current can keep one coastline mild while leaving another unusually [cold|2]. Disruptions to this system could [alter|3] weather patterns across entire [continents|4]." },
    { id:"f3ctw27", taskType:"ctw", title:"Antibiotic resistance", level:"hard", text:"Antibiotics revolutionized medicine by allowing doctors to defeat once-deadly bacterial [infections|4]. Over time, however, some bacteria have evolved the ability to [survive|3] these drugs. Each time an antibiotic is used carelessly, resistant strains gain an [advantage|4] and multiply. Infections that were once easily [treated|4] are becoming dangerous once again. Scientists warn that preserving these medicines requires far more [responsible|4] use [worldwide|4]." },
    { id:"f3ctw28", taskType:"ctw", title:"The water cycle", level:"hard", text:"Water moves endlessly between the oceans, the atmosphere, and the [land|2] in a process known as the water cycle. Heat from the sun causes surface water to [evaporate|4] and rise as invisible vapor. High in the cooler air, this vapor [condenses|4] into clouds of tiny droplets. Eventually the droplets grow heavy and fall back as rain or [snow|2]. Rivers then return much of this water to the [sea|2], and the cycle [repeats|4]." },
    { id:"f3ctw29", taskType:"ctw", title:"Linguistic change", level:"hard", text:"Every living language changes gradually as it passes from one generation to the [next|2]. New words are constantly invented, while older ones quietly fall out of [use|1]. Even pronunciation drifts over the [centuries|4], so that ancient speech would sound strange to modern [ears|2]. Contact between different cultures often [accelerates|4] this process by introducing foreign vocabulary. Linguists study these shifts to reconstruct how languages are historically [related|4]." },
    { id:"f3ctw30", taskType:"ctw", title:"Black holes", level:"hard", text:"A black hole is a region of space where gravity has become so [intense|3] that nothing can escape its pull. Such an object forms when a massive star collapses at the end of its [life|2]. The boundary beyond which escape is impossible is called the event [horizon|4]. Because not even light can leave, the interior remains permanently [hidden|3] from view. Astronomers detect these objects by observing how they [distort|4] the matter and light [around|3] them." }
  ],
  daily: [
    {
      id:"f3dl01",
      taskType:"daily",
      title:"Notice",
      level:"easy",
      text:"ELEVATOR MAINTENANCE NOTICE\n\nThe elevator in Building C will be out of service this Thursday from 8 a.m. until 2 p.m. for its yearly safety inspection. During these hours, residents on all floors must use the stairs at either end of the hallway. We recommend that anyone expecting a large delivery schedule it for another day. If you need special help moving up or down during the closure, please contact the building manager before Wednesday evening. The elevator will return to normal service by mid-afternoon. Thank you for your cooperation and patience while we keep our equipment safe and reliable.",
      q: [
        { stem:"What is the main purpose of the notice?", opts:["To introduce a new building manager","To announce a yearly safety inspection of the elevator","To report that the stairs are being repaired","To describe a new delivery service"], a:1 },
        { stem:"What must residents do during the listed hours?", opts:["Wait in the lobby for assistance","Take the elevator in Building C only","Use the stairs at the ends of the hallway","Leave the building until 2 p.m."], a:2 },
        { stem:"What are people expecting a large delivery advised to do?", opts:["Schedule it for a different day","Ask a neighbor to help carry it","Leave it with the building manager","Use the service elevator instead"], a:0 }
      ]
    },
    {
      id:"f3dl02",
      taskType:"daily",
      title:"Email",
      level:"med",
      text:"Subject: Saturday Photography Club Field Trip\n\nDear members,\n\nThank you for signing up for this Saturday's field trip to the botanical gardens. We will meet at the main gate at 9:15 a.m. sharp, so please arrive a few minutes early. The entrance fee is already covered by your club membership, but bring some money for lunch at the garden cafe. Remember to charge your camera battery the night before and pack a spare memory card. If rain is forecast, we will move the trip to the following Saturday and send an update by Friday noon. Please reply to confirm whether you will bring a guest, as spaces are limited. We look forward to a creative and enjoyable day together.",
      q: [
        { stem:"Why was this email written?", opts:["To cancel the photography club","To advertise a new camera model","To collect the entrance fee from members","To give details about a club field trip"], a:3 },
        { stem:"What are members told to bring money for?", opts:["The entrance fee","Lunch at the garden cafe","A new memory card","Bus tickets to the gardens"], a:1 },
        { stem:"What will happen if rain is forecast?", opts:["The trip will move to the following Saturday","The trip will be cancelled completely","The meeting time will change to noon","Members will meet indoors instead"], a:0 }
      ]
    },
    {
      id:"f3dl03",
      taskType:"daily",
      title:"Post",
      level:"hard",
      text:"Posted in the Maple Street Neighborhood Forum\n\nHas anyone else tried the new tool-lending library at the community center? I borrowed a power drill last week for a small shelf project and was honestly impressed. Instead of spending sixty dollars on a tool I would use once a year, I paid nothing beyond the refundable deposit. The staff even showed me how to use it safely. My only complaint is that the popular items get reserved quickly, so you sometimes have to wait a few days. I would suggest booking online rather than showing up in person. If enough of us support the program, the center has hinted it might extend the opening hours. It seems like a smart way to save money and reduce waste at the same time.",
      q: [
        { stem:"What is the writer's main point about the tool-lending library?", opts:["It is too expensive to be practical","It should be closed because of long waits","It is a useful service worth supporting","It only lends tools to staff members"], a:2 },
        { stem:"Why does the writer suggest booking online?", opts:["Popular items are often reserved quickly","The center charges less for online bookings","The staff are not available in person","Online tools are of higher quality"], a:0 },
        { stem:"What does the writer suggest might happen if the program gets enough support?", opts:["The deposit will no longer be refundable","The center may extend its opening hours","The tools will become free to keep","A second center will open on Maple Street"], a:1 }
      ]
    }
  ],
  academic: [
    {
      id:"f3ap01",
      taskType:"academic",
      title:"The Rise of Standard Time",
      level:"med",
      text:"For most of human history, communities kept time by the position of the sun, which meant that noon in one town might arrive several minutes before or after noon in a town just a short distance to the east or west. When most people rarely traveled far, these small differences caused little trouble. A farmer had no reason to care whether a distant village set its clocks slightly differently. The spread of railways in the nineteenth century, however, made such local timekeeping increasingly impractical.\n\nRailway companies needed to publish schedules that passengers could trust, and this was nearly impossible when every station along a line used its own local time. A train might appear to arrive before it had departed simply because the two towns measured noon differently. To solve this confusion, railway operators began adopting a single standard time across their entire networks, regardless of local solar time. Clocks in stations were synchronized to one agreed reference, often the time kept in the capital city.\n\nThe public did not always welcome the change. Some communities resented having their traditional local time replaced by a distant standard, viewing it as an intrusion on local identity. Yet the practical advantages proved overwhelming. As commerce, communication, and travel expanded, coordinated time became essential. Eventually nations divided the globe into broad time zones, each covering a wide band of longitude and sharing a common clock.\n\nToday we take standardized time entirely for granted, rarely pausing to consider that it was a deliberate human invention rather than a natural feature of the world. The system that allows a traveler to plan a journey across continents grew directly out of the humble need to keep trains running on schedule.",
      q: [
        { stem:"What is the passage mainly about?", opts:["How and why standardized time was adopted","The design of early railway engines","Why farmers disliked traveling by train","How the sun is used to measure longitude"], a:0 },
        { stem:"According to the passage, why did local timekeeping cause little trouble for most of history?", opts:["Clocks were too expensive to own","The sun could not be seen clearly","Every town used the capital's time","Most people rarely traveled far from home"], a:3 },
        { stem:"Why did the spread of railways make local timekeeping impractical?", opts:["Stations on one line used different local times, confusing schedules","Trains could not carry accurate clocks","Passengers refused to buy tickets","The sun moved too quickly for schedules"], a:0 },
        { stem:"The word \"intrusion\" in the passage is closest in meaning to", opts:["a helpful improvement","a careful measurement","an unwelcome interference","a public celebration"], a:2 },
        { stem:"What can be inferred about time zones from the passage?", opts:["They were designed mainly to please farmers","They were created to coordinate time over large areas","They existed long before railways","They follow the exact local time of every town"], a:1 }
      ]
    },
    {
      id:"f3ap02",
      taskType:"academic",
      title:"The Hidden Partnership of Fungi and Roots",
      level:"hard",
      text:"Beneath the floor of nearly every forest lies a hidden partnership so ancient that it may have helped plants colonize dry land in the first place. Most plants form intimate associations with certain fungi, whose thread-like filaments wrap around or even penetrate the plants' roots. These associations, known as mycorrhizae, represent one of the most widespread examples of mutual dependence in the natural world.\n\nThe arrangement benefits both partners. Fungi are remarkably efficient at extracting water and mineral nutrients, particularly phosphorus, from the surrounding soil. Their vast networks of filaments reach into spaces far too small for roots to enter, effectively extending the plant's absorptive surface many times over. In exchange, the plant delivers sugars produced through photosynthesis to the fungus, which cannot manufacture its own food. Neither organism, in most cases, thrives as well alone.\n\nResearch over the past few decades has revealed that these fungal networks can link many separate plants together underground. Through these connections, resources such as carbon and nutrients may flow from one plant to another. Some scientists have proposed that older, well-established trees can support younger seedlings growing in shade by channeling sugars to them along the shared network. The extent and purpose of such transfers remain debated, and researchers caution against romanticizing the phenomenon as deliberate cooperation.\n\nWhat is clear is that the health of a forest depends on far more than the trees visible above ground. Disturbances that damage the soil, such as heavy machinery or certain chemical treatments, can disrupt these delicate networks and weaken the entire ecosystem. Recognizing the importance of the unseen fungal web has changed how ecologists think about forests. Rather than a collection of independent, competing individuals, a forest increasingly appears to be an interconnected community bound together beneath our feet.",
      q: [
        { stem:"What is the main idea of the passage?", opts:["Trees compete fiercely for sunlight in every forest","Fungi are harmful parasites that damage plant roots","Photosynthesis occurs mainly in fungal filaments","Fungi and plant roots form widespread partnerships that shape forest life"], a:3 },
        { stem:"According to the passage, what do fungi provide to plants?", opts:["Water and mineral nutrients from the soil","Sugars made through photosynthesis","Protection from direct sunlight","Seeds for new plants"], a:0 },
        { stem:"What do plants give the fungi in return?", opts:["Phosphorus drawn from the soil","Water stored in their roots","Sugars produced through photosynthesis","Shade from the forest canopy"], a:2 },
        { stem:"The word \"romanticizing\" in the passage is closest in meaning to", opts:["measuring with precision","portraying in an idealized way","destroying carelessly","ignoring completely"], a:1 },
        { stem:"What can be inferred about damaging forest soil?", opts:["It can harm fungal networks and weaken the ecosystem","It has no effect on the trees above ground","It improves the flow of nutrients between plants","It only affects young seedlings"], a:0 }
      ]
    }
  ]
};
